factors:
  factor1:
    slug: f_1
    title: Публикация статьи в рецензируемом издании из списка ВАК, входящем в российскую индексируемую базу РИНЦ
    abbr: ПСвРИ
    grade: 1
  factor2:
    slug: f_2
    title: Публикация статьи в научной периодике, индексируемой иностранными базами данных (Web of Science, Scopus)
    abbr: ПСвНП
    grade: 1
  factor3:
    slug: f_3
    title: Публикация статьи в журнале с импакт - фактором ISI >1
    abbr: ПСвЖ
    grade: 1
  factor4:
    slug: f_4
    title: Публикация монографии
    abbr: ПМ
    grade: 1
  factor5:
    slug: f_5
    title: Получение патента РФ(полезная модель, изобретение), регистрация в Роспатенте программы для ЭВМ или базы данных
    abbr: ПП
    grade: 1
  factor6:
    slug: f_6
    title: Продажа патента и регистрация лицензионного соглашения в Роспатенте
    abbr: ППиРЛС
    grade: 1
  factor7:
    slug: f_7
    title: Медаль государственной академии наук(РАН и др.)
    abbr: МГАН
    grade: 1
  factor8:
    slug: f_8
    title: Медаль международной выставки(Золотая)
    abbr: ММВ
    grade: 1
  factor9:
    slug: f_9
    title: Диплом I степени на международном конкурсе научных проектов
    abbr: ДIC
    grade: 1
  factor10:
    slug: f_10
    title: Защита кандидатской диссертации в срок
    abbr: ЗКК
    grade: 1
  factor11:
    slug: f_11
    title: Защита докторской диссертации в срок
    abbr: ЗДД
    grade: 1
  factor12:
    slug: f_12
    title: Работа в диссертационном совете ТУСУРа или других диссертационных советах
    abbr: РвДС
    grade: 1
  factor13:
    slug: f_13
    title: Участие в международных конференциях
    abbr: УвМК
    grade: 1
  factor14:
    slug: f_14
    title: Участие в выполнении НИР
    abbr: УвВНИР
    grade: 1
  factor15:
    slug: f_15
    title: Обеспечение экспорта высокотехнологичных товаров и услуг (участие в экспортных контрактах ТУСУРа)
    abbr: ОЭВТиУ
    grade: 1
  factor16:
    slug: f_16
    title: Количество цитирований статей автора в журналах, индесируемых иностранными базами данных(Web of Science, Scopus)
    abbr: КЦСФвЖ
    grade: 1
  factor17:
    slug: f_17
    title: Наличие в электронной форме на образовательном портале ТУСУРа полного своего комплекта УМКД(все компоненты не страше 3 лет)
    abbr: КУМКВД
    grade: 1
  factor18:
    slug: f_18
    title: Руководство группой ГПО, занявшей призовое место в конкурсах всех уровней в отчетном календарном году
    abbr: РГГПО
    grade: 1
  factor19:
    slug: f_19
    title: Оценка в анкетах студентами в текущем учебном году(средний балл)
    abbr: ОвАС
    grade: 1
  factor20:
    slug: f_20
    title: Наличие изданного авторского (в соавторстве) учебника по преподаваемой дисциплине(не более 5 летней давности)
    abbr: НИАУ
    grade: 1
  factor21:
    slug: f_21
    title: Наличие типографского изданного с грифом Минобразования РФ авторского(в соавторстве) учебного пособия, лабораторного практикума, текста лекций, сборника задач, авторского пособия/методических указаний (МУ) по СРС, МУ для курсового проекта/работы, МУ для дипломного проекта/работы, МУ для практики(по преподаваемой дисциплине и не более 5 летней давности)
    abbr: НТИУП
    grade: 1
  factor22:
    slug: f_22
    title: Разработка рабочего учебного плана или основной образовательной программы по направлени/специальности кафедры(не старше 2 лет)
    abbr: РРУП
    grade: 1
  factor23:
    slug: f_23
    title: Победа в конкурсе Лучший куратор года в ТУСУРе
    abbr: ЛКГ
    grade: 1
  factor24:
    slug: f_24
    title: Преподавательская и учебно - методическая деятельность на иностранном языке, в т. ч. в рамках программ двойных дипломов с зарубежными университетами - партнерами 
    abbr: ПиУМДнИЯ
    grade: 1
  factor25:
    slug: f_25
    title: Организация в ТУСУРе учебно - научной лаборатории с международным участием
    abbr: ОУНЛ
    grade: 1
  factor26:
    slug: f_26
    title: Получение международного гранта через ТУСУР 
    abbr: ПМГ
    grade: 1
  factor27:
    slug: f_27
    title: Прохождение целевой зарубежной стажировки за счет полученного гранта, участия в совместных проектах
    abbr: ПЦЗС
    grade: 1
  factor28:
    slug: f_28
    title: Участие в оргкомитете международной конференции, проводимой за рубежом
    abbr: УвОМК
    grade: 1
